### ISSUE TITLE
Error: User directory is not /home/root

### ISSUE THREAD

**Issue by Etunts** [thefloppydriver/pc2drc#9]
did everything correctly and successfully.
fresh installed ubuntu 18.04 just for this process.

(there were some other problems but i fixed them. so i deleted them.)

**Comment by Etunts** [comment]
i fixed it.
now i have the issue 
vnc viewer error: unable connect to socket: Connection refused (111) 
on tiger vnc

and
runuser: user thefloppydriver does not exist
on terminal

**Comment by Etunts** [comment]
WiFi Interfaces:
  0: wlp2s0

Which wireless interface would you like to use to stream to the WiiU Gamepad?
Input (Number): 0
Starting VNC server...
runuser: user thefloppydriver does not exist
VNC Server started successfully.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 150, in read_nonblocking
    s = os.read(self.child_fd, size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 99, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 465, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 155, in read_nonblocking
    raise EOF('End Of File (EOF). Exception style platform.')
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./stage-4-start-pc2drc.py", line 219, in <module>
    vncviewer.expect(" Connected to host", timeout=10)
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 105, in expect_loop
    return self.eof(e)
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 50, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x7f8af34b0860>
command: /usr/bin/xtigervncviewer
args: ['/usr/bin/xtigervncviewer', '-SecurityTypes', 'None', ':1', '-DesktopSize=854x480']
buffer (last 100 chars): b''
before (last 100 chars): b"ttp://www.tigervnc.org for information on TigerVNC.\r\nNo protocol specified\r\nCan't open display: :0\r\n"
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 4888
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile("b' Connected to host'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./stage-4-start-pc2drc.py", line 221, in <module>
    print(vncserver.before.decode('utf-8'))
NameError: name 'vncserver' is not defined

**Comment by Etunts** [comment]
i also fixed it.

now i have this issue
mamaluigi@mamaluigi:~/pc2drc$ sudo ./start-pc2drc.sh
WiFi Interfaces:
  0: wlp2s0

Which wireless interface would you like to use to stream to the WiiU Gamepad?
Input (Number): 0
Starting VNC server...
runuser: user thefloppydriver does not exist
VNC Server started successfully.

TigerVNC Viewer 64-bit v1.7.0
Built on: 2017-12-05 09:25
Copyright (C) 1999-2016 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
No protocol specified
Can't open display: :0







TigerVNC Viewer 64-bit v1.7.0
Built on: 2017-12-05 09:25
Copyright (C) 1999-2016 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
No protocol specified
Can't open display: :0

Could not connect to vncserver. Please restart the program and try again.
(press enter to quit)

**Comment by Etunts** [comment]
now it only gives the 111 error.

**Comment by Etunts** [comment]
CConn:       unable connect to socket: Connection refused (111)

**Comment by Special-Niewbie** [comment]
Hello @Etunts , please ,how did you solved the error: `User directory is not /home/root`

Because I'm facing the same issue on `stage-3-pair-with-wiiu.py`

Thank you

**Comment by Etunts** [comment]
no need to talk formal too.

**Comment by Special-Niewbie** [comment]
Thank you man, it works..... and I have the same 111 Error connection related VNC server connection.

Later I will open a new thread with this problem (now I have to go out), because I tracked all the error history during the installation stages, and I believe this error it's related to some first steps installation error.

**Comment by thefloppydriver** [comment]
I'll take a look at this tomorrow.

**Comment by Etunts** [comment]
Hi?

**Comment by Special-Niewbie** [comment]
Hello @Etunts and happy Easter to all,

the problem of this error it's not related to @thefloppydriver and mod his files, but the problem come from a bug into the Linux Kernel version `5.4.0-107-generic` or `5.4.0-105-generic` related to the permissions....

So, after some kernel version testing from my side (using Mainline software to track which Kernel I'm installing and testing), the best Kernel that I can build everything without Errors, it's the Kernel `5.11.10-051110-generic`

But, only two things still persist as error, and it's that cannot Patch the kernel in the last moment on Stage one ( but doesn't give any error about the services because are installed ) and the VNCserver error building on Stage two (even if in the end it writes `All modules built successfully! Onto stage 3!`

This problem, in this topic  can be close as done....
